# Generated by Django 4.2.7 on 2024-06-24 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuploadfile',
            name='extracted_text',
            field=models.TextField(default=''),
        ),
    ]
